Creating NumPy arrays

In [1]:
import numpy as np

In [2]:
# create a 1-dimensional array

In [3]:
a = np.array([1,2,3,4,5])

In [32]:
a

array([4, 3, 7])

In [5]:
# create a 2-dimensional array

In [6]:
b = np.array([[1, 2, 3],[4, 5, 6]])

In [31]:
b

array([7, 4, 1])

In [8]:
# create an array of zeros

In [9]:
c = np.zeros((3,4))

In [30]:
c

array([11,  7,  8])

In [11]:
# create an array of ones

In [12]:
d = np.ones((2,2))

In [13]:
d

array([[1., 1.],
       [1., 1.]])

Performing mathematical operation on NumPy arrays

In [14]:
# add two arrays

In [16]:
a = np.array([4, 3, 7])

In [17]:
b = np.array([7, 4, 1])

In [18]:
c = a + b

In [19]:
c

array([11,  7,  8])

In [20]:
# multiply two arrays

In [21]:
d = np.array([[3, 4],[6, 2]])

In [22]:
e = np.array([[3, 4],[7, 2]])

In [23]:
f = d * e

In [24]:
f

array([[ 9, 16],
       [42,  4]])

In [25]:
# perform matrix multiplication

In [26]:
g = np.array([[3, 3],[4, 4]])

In [27]:
h = np.array([[5, 4],[6, 3]])

In [28]:
i = np.dot(g, h)

In [29]:
i

array([[33, 21],
       [44, 28]])